<a href="https://colab.research.google.com/github/nimit13/machine-learning/blob/master/8x2numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as npy

a=npy.arange(100,125,1)

for i in a:
  j=i+80
  b=npy.arange(i,j,5)
  b.shape=(8,2)
  print(b)
  print("\n",i-99,"\n")


[[100 105]
 [110 115]
 [120 125]
 [130 135]
 [140 145]
 [150 155]
 [160 165]
 [170 175]]

 1 

[[101 106]
 [111 116]
 [121 126]
 [131 136]
 [141 146]
 [151 156]
 [161 166]
 [171 176]]

 2 

[[102 107]
 [112 117]
 [122 127]
 [132 137]
 [142 147]
 [152 157]
 [162 167]
 [172 177]]

 3 

[[103 108]
 [113 118]
 [123 128]
 [133 138]
 [143 148]
 [153 158]
 [163 168]
 [173 178]]

 4 

[[104 109]
 [114 119]
 [124 129]
 [134 139]
 [144 149]
 [154 159]
 [164 169]
 [174 179]]

 5 

[[105 110]
 [115 120]
 [125 130]
 [135 140]
 [145 150]
 [155 160]
 [165 170]
 [175 180]]

 6 

[[106 111]
 [116 121]
 [126 131]
 [136 141]
 [146 151]
 [156 161]
 [166 171]
 [176 181]]

 7 

[[107 112]
 [117 122]
 [127 132]
 [137 142]
 [147 152]
 [157 162]
 [167 172]
 [177 182]]

 8 

[[108 113]
 [118 123]
 [128 133]
 [138 143]
 [148 153]
 [158 163]
 [168 173]
 [178 183]]

 9 

[[109 114]
 [119 124]
 [129 134]
 [139 144]
 [149 154]
 [159 164]
 [169 174]
 [179 184]]

 10 

[[110 115]
 [120 125]
 [130 135]
 [140 145]
 [150